# -*- coding: utf-8 -*-
db.admin_settings.insert(variable_name="max_rebook_days",variable_value=28,description="Sets the max number of days forward an enduser can see rebookable dates")
db.admin_settings.insert(variable_name="active_semester",variable_value=1,description="Stores the active semester, changed by user")
db.admin_settings.insert(variable_name="hours_before_canx",variable_value=4,description="Set the time 4 hours before the leason beginsit is cancellable. ")
db.semester.insert(name="Hostterminen 2013",start_date="2013-08-12",end_date="2013-12-22")
db.skill_level.insert(skill_name="Nivå 1",skill_point=1,skill_type="Ponny")
db.skill_level.insert(skill_name="Nivå 2",skill_point=2,skill_type="Ponny")
db.leason.insert(week_day="Måndag",leason_time="18:00:00",leason_length=60,max_customers=6, skill_level=1,status="Active",leason_type="Ponny")
db.leason.insert(week_day="Tisdag",leason_time="18:00:00",leason_length=60,max_customers=6, skill_level=1,status="Active",leason_type="Ponny")
db.leason.insert(week_day="Onsdag",leason_time="18:00:00",leason_length=60,max_customers=6, skill_level=2,status="Active",leason_type="Ponny")
db.leason.insert(week_day="Torsdag",leason_time="18:00:00",leason_length=60,max_customers=6, skill_level=1,status="Active",leason_type="Ponny")
db.leason.insert(week_day="Fredag",leason_time="18:00:00",leason_length=60,max_customers=6, skill_level=2,status="Active",leason_type="Ponny")
db.leason.insert(week_day="Lördag",leason_time="18:00:00",leason_length=60,max_customers=6, skill_level=2,status="Active",leason_type="Ponny")
db.leason.insert(week_day="Söndag",leason_time="18:00:00",leason_length=60,max_customers=6, skill_level=1,status="Active",leason_type="Ponny")
db.customer.insert(name="Rikard Rikardsson",status="Active")
db.leasons.insert(id_customer=1,id_leason=1)
db.leasons.insert(id_customer=1,id_leason=2)
db.leasons.insert(id_customer=1,id_leason=4)
db.leasons.insert(id_customer=1,id_leason=6)

db.instructor.insert(name="Johnny Jönsson")
db.instructor.insert(name="Svullo Svinsta")
db.owner_of_leason.insert(leason_id=1,instructor_id=1)
db.owner_of_leason.insert(leason_id=2,instructor_id=2)
db.owner_of_leason.insert(leason_id=3,instructor_id=1)
db.owner_of_leason.insert(leason_id=4,instructor_id=2)
db.owner_of_leason.insert(leason_id=4,instructor_id=1)
db.commit()
